version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8  # Choose an appropriate Python version
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 605134465349.dkr.ecr.us-east-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t flask-app .
      - docker tag flask-app:latest 605134465349.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 605134465349.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
artifacts:
  files:
    - app.py
    - Dockerfile
    - requirements.txt