version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install awscli --upgrade
  pre_build:
    commands:
      - echo Logging in to Amazon ECR Public...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t sairajapp .
      - docker tag sairajapp:latest public.ecr.aws/i4a2a9c3/sairajapp:latest
      - docker push public.ecr.aws/i4a2a9c3/sairajapp:latest
      - echo Build completed on `date`
      - printf '[{"name":"sairaj-container","imageUri":"%s"}]' public.ecr.aws/i4a2a9c3/sairajapp:latest > imagedefinitions.json
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/i4a2a9c3/sairajapp:latest
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
    - 'imagedefinitions.json'
